version: "3.7"
services:
  php:
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./www/:/var/www/html/
    ports:
      - 80:80
      - 443:443