version: "4.3"
services:

  db:
    container_name: mariadb
    image: mariadb:10.9
    command: mysqld --sql_mode=
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./conf/db:/var/lib/mysql

  app-php:
    container_name: "php${PHP_VERSION}-apache"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TIMEZONE=${TIMEZONE}
        - PHP_VERSION=${PHP_VERSION}
    env_file:
      - .env
    volumes:
      - ./www/:/var/www/html
      #- ./conf/php/php.ini:/etc/php/${PHP_VERSION}/apache2/php.ini
      - ./conf/ssl/localhost.crt:/etc/ssl/ca/localhost.crt
      - ./conf/ssl/localhost.key:/etc/ssl/ca/localhost.key
      - ./conf/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 80:80
      - 443:443
    links:
      - db
    depends_on:
      - db
    tty: true

  app-nodejs: 
    container_name: "nodejs"
    image: node:18
    command: /bin/bash
    volumes:
      - ./www/:/var/www/html
    ports:
      - 8000:8000
    tty: true