version: "5.0"
services:

  db:
    container_name: "mariadb"
    image: "mariadb:10.4"
    command: ["mysqld", "--sql_mode=", "--default_time_zone=America/Sao_Paulo"]
    ports:
      - 3306:3306
    volumes:
      - ./conf/db:/var/lib/mysql

  php:
    container_name: "php-apache"
    build:
      context: .
    volumes:
      - ./www/:/var/www/html/
      - ./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./conf/ssl/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./conf/ssl/localhost.key:/etc/ssl/private/localhost.key
      - ./conf/apache/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 80:80
      - 443:443
    links:
      - db
    depends_on:
      - db